/**
 * @generated
 * @file Button (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://rebel-dashboard.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import BlockContainer from "./webflow_modules/Layout/components/BlockContainer";
import Image from "./webflow_modules/Basic/components/Image";
import Link from "./webflow_modules/Basic/components/Link";
import Section from "./webflow_modules/Layout/components/Section";

/**
 * Props for {@link Button}
 */
export type ButtonProps = {
  image?: string;
  link?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  text?: React.ReactNode;
};

/**
 * Button
 *
 * @see {@link https://rebel-dashboard.design.webflow.com | Source site in Webflow}
 */
export function Button({
  image = "https://cdn.prod.website-files.com/6994ad8d279287de73c3a891/6a017c2e64ec541893922a84_generic.svg",

  link = {
    href: "#",
  },

  text = "[ Icon Button ] ",
}: ButtonProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"component_headlne-4-subsections"} tag={"div"}>
        <Section
          className={"component_wrapper component_button"}
          grid={{
            type: "section",
          }}
          tag={"section"}
        >
          <BlockContainer
            className={"component_container component_button-margin"}
            grid={{
              type: "container",
            }}
            tag={"div"}
          >
            <Block
              className={"component-button_color-variants color-primary"}
              tag={"div"}
            >
              <Block
                className={"slot_button-color color-primary-2"}
                tag={"div"}
              >
                <Block className={"button-variant_wrapper"} tag={"div"}>
                  <Link
                    block={""}
                    button={true}
                    className={"buton-variant"}
                    options={link}
                  >
                    {text}
                  </Link>
                  <Block className={"icon_wrapper"} tag={"div"} />
                </Block>
              </Block>
            </Block>
          </BlockContainer>
        </Section>
      </Block>
    </div>
  );
}
