/**
 * @generated
 * @file MetricType (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://rebel-dashboard.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import { MetricLayout } from "./MetricLayout";
import { applyPredicate } from "./webflow_modules/Conditions/helpers/applyPredicate";
import { styleVariantIsAny } from "./webflow_modules/Basic/helpers/styleVariantIsAny";

/**
 * Props for {@link MetricType}
 */
export type MetricTypeProps = {
  abbreviatedMetric?: boolean;
  displayMetric?: boolean;
  iconTrendIndicatorRuntimeProps?: Record<string, unknown>;
  iconTrendVisibility?: boolean;
  layout?:
    | "Base"
    | "Stacked 1col"
    | "Stacked 2col"
    | "Horizontal 1row"
    | "Horizontal 2row";
  metricLayoutMetricValue?: React.ReactNode;
  metricLayoutMetricVariance?: React.ReactNode;
  metricLayoutValueFormat?: string;
  metricRuntimeProps?: Record<string, unknown>;
  metricType?:
    | "Base"
    | "Occupancy"
    | "Rooms"
    | "ADR"
    | "Revenue"
    | "RevPar"
    | "Nights"
    | "Reservations"
    | "Guests";
  varianceLabelVisibility?: boolean;
  varianceMetricRuntimeProps?: Record<string, unknown>;
  varianceMetricVisibility?: boolean;
  varianceType?: "Base" | "TO-BOOK" | "%CHG" | "VAR" | "LY" | "STLY" | "WOW";
};

/**
 * MetricType
 *
 * @see {@link https://rebel-dashboard.design.webflow.com | Source site in Webflow}
 */
export function MetricType({
  abbreviatedMetric = false,
  displayMetric = false,
  iconTrendIndicatorRuntimeProps = {},
  iconTrendVisibility = true,
  layout = "Horizontal 2row",
  metricLayoutMetricValue = "0.0%",
  metricLayoutMetricVariance = "0.0%",
  metricLayoutValueFormat = "",
  metricRuntimeProps = {},
  metricType = "Base",
  varianceLabelVisibility = true,
  varianceMetricRuntimeProps = {},
  varianceMetricVisibility = true,
  varianceType = "Base",
}: MetricTypeProps) {
  const _styleVariantMap = {
    Base: "",
    Occupancy: "w-variant-840e49f9-c7e1-c99f-20ad-590baef4b13f",
    Rooms: "w-variant-dfb3022a-7e3d-78d2-88e5-e7225577a541",
    ADR: "w-variant-452a1012-a794-3482-1f24-c0d146b9f2df",
    Revenue: "w-variant-466d4594-9b99-6ec0-5480-0bbe181b5285",
    RevPar: "w-variant-31ee03ce-538e-d645-bc5f-e3f564b7a7c9",
    Nights: "w-variant-737a8317-d602-a65c-ba99-d8642d5c3810",
    Reservations: "w-variant-d01044fd-794c-3a94-7ae5-0e8e2b975ac3",
    Guests: "w-variant-3c73d169-68b8-88d7-7ca8-bfde87b648c6",
  };

  const _activeStyleVariant = _styleVariantMap[metricType];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={`metric-container ${_activeStyleVariant}`} tag={"div"}>
        <MetricLayout
          iconTrendRuntimeProps={iconTrendIndicatorRuntimeProps}
          iconTrendVisibility={iconTrendVisibility}
          layoutVariant={layout}
          metricType={
            abbreviatedMetric &&
            applyPredicate(metricType)(styleVariantIsAny(["Occupancy"]))
              ? ["Occp"]
              : !abbreviatedMetric &&
                applyPredicate(metricType)(styleVariantIsAny(["Occupancy"]))
              ? ["Occupancy"]
              : applyPredicate(metricType)(styleVariantIsAny(["ADR"]))
              ? ["ADR"]
              : abbreviatedMetric &&
                applyPredicate(metricType)(styleVariantIsAny(["Revenue"]))
              ? ["Rev"]
              : !abbreviatedMetric &&
                applyPredicate(metricType)(styleVariantIsAny(["Revenue"]))
              ? ["Revenue"]
              : applyPredicate(metricType)(styleVariantIsAny(["RevPar"]))
              ? ["RevPar"]
              : abbreviatedMetric &&
                applyPredicate(metricType)(styleVariantIsAny(["Reservations"]))
              ? ["Resvn"]
              : !abbreviatedMetric &&
                applyPredicate(metricType)(styleVariantIsAny(["Reservations"]))
              ? ["Reservations"]
              : abbreviatedMetric &&
                applyPredicate(metricType)(styleVariantIsAny(["Nights"]))
              ? ["Nts"]
              : !abbreviatedMetric &&
                applyPredicate(metricType)(styleVariantIsAny(["Nights"]))
              ? ["Nights"]
              : applyPredicate(metricType)(styleVariantIsAny(["Guests"]))
              ? ["Guests"]
              : ["Metric"]
          }
          metricValue={metricLayoutMetricValue}
          metricVariance={metricLayoutMetricVariance}
          metricVarRuntimeProps={varianceMetricRuntimeProps}
          valueFormat={metricLayoutValueFormat}
          varianceFormat={
            applyPredicate(varianceType)(styleVariantIsAny(["%CHG"])) &&
            applyPredicate(metricType)(
              styleVariantIsAny([
                "Occupancy",
                "Rooms",
                "ADR",
                "Revenue",
                "RevPar",
                "Nights",
                "Reservations",
                "Guests",
              ])
            )
              ? "+/- 0.0%"
              : applyPredicate(varianceType)(
                  styleVariantIsAny(["VAR", "STLY", "LY", "WOW"])
                ) &&
                applyPredicate(metricType)(styleVariantIsAny(["Occupancy"]))
              ? "+/- 0.0%"
              : applyPredicate(varianceType)(
                  styleVariantIsAny(["VAR", "STLY", "LY", "WOW", "TO-BOOK"])
                ) &&
                applyPredicate(metricType)(
                  styleVariantIsAny([
                    "Rooms",
                    "Nights",
                    "Reservations",
                    "Guests",
                  ])
                )
              ? "+/- 0,000"
              : applyPredicate(varianceType)(
                  styleVariantIsAny(["VAR", "TO-BOOK", "STLY", "LY", "WOW"])
                ) &&
                applyPredicate(metricType)(styleVariantIsAny(["ADR", "RevPar"]))
              ? "+/- $0,000.00"
              : applyPredicate(varianceType)(
                  styleVariantIsAny(["VAR", "STLY", "TO-BOOK", "LY", "WOW"])
                ) && applyPredicate(metricType)(styleVariantIsAny(["Revenue"]))
              ? "+/- $0,000"
              : "0.00"
          }
          varianceLabel={
            applyPredicate(varianceType)(styleVariantIsAny(["TO-BOOK"]))
              ? ["to book"]
              : applyPredicate(varianceType)(styleVariantIsAny(["%CHG"]))
              ? ["%chg"]
              : applyPredicate(varianceType)(styleVariantIsAny(["VAR"]))
              ? ["var"]
              : applyPredicate(varianceType)(styleVariantIsAny(["STLY"]))
              ? ["var STLY"]
              : applyPredicate(varianceType)(styleVariantIsAny(["LY"]))
              ? ["var PY"]
              : applyPredicate(varianceType)(styleVariantIsAny(["WOW"]))
              ? ["var WOW"]
              : ["var"]
          }
          varianceLabelVisibility={varianceLabelVisibility}
          varianceType={varianceType}
          varianceVisibility={varianceMetricVisibility}
        />
      </Block>
    </div>
  );
}
