/**
 * @generated
 * @file VariantsFontSize (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://rebel-dashboard.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";

/**
 * Props for {@link VariantsFontSize}
 */
export type VariantsFontSizeProps = {
  slot?: React.ReactNode;
  variant?: "sm" | "Base" | "md" | "lg" | "xl" | "xxl";
};

/**
 * VariantsFontSize
 *
 * @see {@link https://rebel-dashboard.design.webflow.com | Source site in Webflow}
 */
export function VariantsFontSize({
  slot,
  variant = "Base",
}: VariantsFontSizeProps) {
  const _styleVariantMap = {
    sm: "w-variant-4d6cde0b-241b-86a1-e782-8cc43955fd35",
    Base: "",
    md: "w-variant-f36ecebd-6c42-b3f4-91ca-ba4646749027",
    lg: "w-variant-55d50f96-5e1e-77d4-f3dd-aa336a51e033",
    xl: "w-variant-23efab10-9326-c25e-ba47-9a0e83cf7b2d",
    xxl: "w-variant-87068ecb-5d19-1f8c-315c-82c326fe63b2",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={`slot_font-size ${_activeStyleVariant}`} tag={"div"}>
        {slot}
      </Block>
    </div>
  );
}
