/**
 * @generated
 * @file VarianceMetric (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://rebel-dashboard.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import HtmlEmbed from "./webflow_modules/Embed/components/HtmlEmbed";
import { applyPredicate } from "./webflow_modules/Conditions/helpers/applyPredicate";
import { styleVariantIsAny } from "./webflow_modules/Basic/helpers/styleVariantIsAny";

/**
 * Props for {@link VarianceMetric}
 */
export type VarianceMetricProps = {
  displayMetricValueVisibility?: boolean;
  displayMetricVarianceVisibility?: boolean;
  metricValue?: React.ReactNode;
  varianceFormat?: string;
  varianceType?: "Base" | "TO-BOOK" | "%CHG" | "VAR" | "LY" | "STLY" | "WOW";
};

/**
 * VarianceMetric
 *
 * @see {@link https://rebel-dashboard.design.webflow.com | Source site in Webflow}
 */
export function VarianceMetric({
  displayMetricValueVisibility = true,
  displayMetricVarianceVisibility = true,
  metricValue = "0.0%",
  varianceFormat = "",
  varianceType = "STLY",
}: VarianceMetricProps) {
  const _styleVariantMap = {
    Base: "",
    "TO-BOOK": "w-variant-5a208db1-adb0-5415-f462-a9f23d8d06a3",
    "%CHG": "w-variant-16fa5099-487d-73c7-7798-152461567107",
    VAR: "w-variant-55e9aca6-2b1c-5de3-ba3a-18938ab2661f",
    LY: "w-variant-f8900bb6-67b5-ad07-be87-4fcb77d764c9",
    STLY: "w-variant-495572c8-ad31-9ce2-be19-3b503ecb11e9",
    WOW: "w-variant-9f73190f-f31f-dc92-ccc5-5e12cda25509",
  };

  const _activeStyleVariant = _styleVariantMap[varianceType];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block
        className={`variant_metric-var-wrapper ${_activeStyleVariant}`}
        tag={"div"}
      >
        {displayMetricValueVisibility ? (
          <Block
            className={`metric-value_container ${_activeStyleVariant}`}
            tag={"div"}
          >
            <Block
              className={`metric-value ${_activeStyleVariant}`}
              tag={"div"}
              variance-format={varianceFormat}
            >
              {metricValue}
            </Block>
            <Block
              className={`icon-wrapper-circle is-positive _85em ${_activeStyleVariant}`}
              tag={"div"}
            >
              <HtmlEmbed
                className={`arrow-icon ${_activeStyleVariant}`}
                content={""}
                value={
                  "%3Csvg%20viewBox%3D%220%200%20100%20100%22%20fill%3D%22currentColor%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Cpath%20d%3D%22M78.016%2049.132L51.961%2012.714c-.471-.66-1.233-1.049-2.043-1.051%20-.006%200-.006%200-.006%200%20-.815.002-1.575.396-2.048%201.059L21.977%2049.14c-.546.767-.616%201.776-.183%202.612%20.426.835%201.292%201.361%202.236%201.361h12.183l-.001%2032.709c0%201.39%201.125%202.515%202.516%202.515l22.541-.001c1.389.001%202.515-1.124%202.516-2.517V53.114h12.187c.94%200%201.803-.53%202.237-1.367%20.432-.836.357-1.847-.193-2.615Z%22%2F%3E%3C%2Fsvg%3E"
                }
              />
            </Block>
          </Block>
        ) : null}
        {displayMetricVarianceVisibility ? (
          <Block
            className={`metric-var_container ${_activeStyleVariant}`}
            tag={"div"}
          >
            <Block
              className={`metric-var ${_activeStyleVariant}`}
              tag={"div"}
              variance-format={varianceFormat}
            >
              {metricValue}
            </Block>
            <Block
              className={`metric-var-label ${_activeStyleVariant}`}
              tag={"div"}
            >
              {applyPredicate(varianceType)(styleVariantIsAny(["TO-BOOK"]))
                ? ["TO-BOOK"]
                : applyPredicate(varianceType)(styleVariantIsAny(["%CHG"]))
                ? ["%CHG"]
                : applyPredicate(varianceType)(styleVariantIsAny(["VAR"]))
                ? ["VAR"]
                : applyPredicate(varianceType)(styleVariantIsAny(["LY"]))
                ? ["LY"]
                : applyPredicate(varianceType)(styleVariantIsAny(["STLY"]))
                ? ["STLY"]
                : applyPredicate(varianceType)(styleVariantIsAny(["WOW"]))
                ? ["WOW"]
                : ["STLY"]}
            </Block>
          </Block>
        ) : null}
      </Block>
    </div>
  );
}
